server:
  port: 8000

keycloak:
  realm: my_realm
  auth-server-url: http://localhost:8080
  ssl-required: external
  resource: my_client
  credentials:
    secret: jJGo9sCxMFUKmxMDHmgLO5BDfbVVJTGs
  use-resource-role-mappings: true
  bearer-only: true

logging:
  level:
    root: INFO
    com.psc.sample.keycloak: DEBUG